databases:
  - name: myapp
    databaseName: myapp
    user: myapp

services:
  - type: web
    name: myapp 
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false